name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    pull_request:
      branches:
        - 'main'

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run unit tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:${{ github.workspace }}/src/"
          python3 -m unittest discover test/ -v

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [ unit_tests ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: gravity981/3dgen
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [ push_to_registry ]
    steps:
      - name: generate test models
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: gravity981/3dgen:main
          options: -v ${{ github.workspace }}:/work --user root
          run: ./test/integration_tests.sh