name: publish release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y openscad
          ./scripts/install_fonts.sh

      - name: Generate 3D Tokens
        run: |
          ./scripts/generate_all_tokens.sh
          ./scripts/stitch_thumbnails.sh
      
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "token_package"
          path: |
            output
            
  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: bump version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - name: push version new version tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
        
      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: "token_package"
        
      - name: zip artifacts
        uses: thedoctor0/zip-release@master
        with:
          path: './token_package/3d'
          type: 'zip'
          filename: 'token_package.zip'

      - name: publish github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            "./token_package.zip"
            "./token_package/poster.png"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bump-semver.outputs.new_version }}
          draft: true
