name: publish release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y openscad

      - name: Create 3D Tokens
        run: ./create_all_tokens.sh
