name: publish models

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_VERSION: "2.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Generate 3D Models
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: gravity981/3dgen:${{ env.DOCKER_IMAGE_VERSION }}
          options: -v ${{ github.workspace }}:/work --user root
          run: /usr/bin/generate_3d_models.sh -m models -c config/all_tokens.json -o output/tokens -t -p
      
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "token_package"
          path: |
            output/tokens
            
  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: "token_package"
        
      - name: zip artifacts
        uses: thedoctor0/zip-release@master
        with:
          path: './token_package/3d'
          type: 'zip'
          filename: 'token_package.zip'

      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: publish github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "token_package.zip,token_package/poster.png"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: ${{ steps.get-latest-tag.outputs.tag }}
          body: |
            based on config of revision ${{ github.sha }}
            ![poster](${{ github.server_url }}/${{ github.repository }}/releases/download/<EDIT_THIS>/poster.png)
          name: "Models-${{ env.DOCKER_IMAGE_VERSION }}-${{ github.run_number }}"
