name: publish models

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_VERSION: "3.1.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Generate 3D Models
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: gravity981/3dgen:${{ env.DOCKER_IMAGE_VERSION }}
          options: -v ${{ github.workspace }}:/work --user root
          run: |
            /usr/bin/model_generator_wrapper.sh -m models -c /conf/all_tokens.json -o output/tokens -t -p
            /usr/bin/model_generator_wrapper.sh -m models -c /conf/all_smartphone_samsung_s20_cases.json -o output/smartphone_samsung_s20_cases -t -p
            /usr/bin/model_generator_wrapper.sh -m models -c /conf/all_smartphone_iphone_13_cases.json -o output/smartphone_iphone_13_cases -t -p

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "model_package"
          path: |
            output/tokens
            output/smartphone_samsung_s20_cases
            output/smartphone_iphone_13_cases

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: "model_package"
        
      - name: zip artifacts
        uses: thedoctor0/zip-release@master
        with:
          path: './model_package'
          type: 'zip'
          filename: 'model_package.zip'

      - name: list files
        run: tree ./model_package

      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: publish github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "model_package.zip,./model_package/*/*.png"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: ${{ steps.get-latest-tag.outputs.tag }}
          body: |
            based on config of revision ${{ github.sha }}
            ![poster](${{ github.server_url }}/${{ github.repository }}/releases/download/<EDIT_THIS>/poster.png)
          name: "Models-${{ env.DOCKER_IMAGE_VERSION }}-${{ github.run_number }}"
